title: 20180415 Team HⅡ New H Stars 03
datetime: 2018-04-15T14:00:00+08:00
vod: http://zhibo.ckg48.com/Index/invedio/id/538
m3u8: http://ts.snh48.com/chaoqing/9999/20180415133549-playlist.m3u8?beginTime=20180415140000&endTime=20180415165200
tags:
- SNH48
- New H Stars
- Team HⅡ
- HⅡ
- Team HII
- HII
thumbnail: 20180415-New H Stars-03.png
playlists:
- 全部
- 全部公演
- Team HⅡ
- Team HⅡ — New H Stars
