title: 20180316 电玩美少女之萌神降临
datetime: 2018-03-16T17:45:00+08:00
vod: http://zhibo.ckg48.com/Index/invedio/id/517
m3u8: http://ts.snh48.com/vod/sanguo-MPEG4.mp4/playlist.m3u8
tags:
- SNH48
thumbnail: 
playlists:
- 全部
- 全部公演
- 特别公演
