title: 20180422 Team HⅡ New H Stars 04
datetime: 2018-04-22T19:00:00+08:00
vod: http://zhibo.ckg48.com/Index/invedio/id/551
m3u8: http://ts.snh48.com/chaoqing/9999/20180422185724-playlist.m3u8?beginTime=20180422190000&endTime=20180422221200
tags:
- SNH48
- New H Stars
- Team HⅡ
- HⅡ
- Team HII
- HII
thumbnail: 20180422-New H Stars-04.png
playlists:
- 全部
- 全部公演
- Team HⅡ
- Team HⅡ — New H Stars
