title: 20180330 Team HⅡ New H Stars 01
datetime: 2018-03-30T19:30:00+08:00
vod: http://zhibo.ckg48.com/Index/invedio/id/525
m3u8: http://ts.snh48.com/chaoqing/9999/20180330173502-playlist.m3u8?beginTime=20180330193000&endTime=20180330220700
tags:
- SNH48
- New H Stars
- Team HⅡ
- HⅡ
- Team HII
- HII
thumbnail: 20180330-New H Stars-01.png
playlists:
- 全部
- 全部公演
- Team HⅡ
- Team HⅡ — New H Stars
