title: 20180428 Team HⅡ New H Stars 05
datetime: 2018-04-28T19:30:00+08:00
vod: http://zhibo.ckg48.com/Index/invedio/id/557
m3u8: http://ts.snh48.com/chaoqing/9999/20180428185154-playlist.m3u8?beginTime=20180428193000&endTime=20180428213900
tags:
- SNH48
- New H Stars
- Team HⅡ
- HⅡ
- Team HII
- HII
thumbnail: 20180428-New H Stars-05.png
playlists:
- 全部
- 全部公演
- Team HⅡ
- Team HⅡ — New H Stars
