title: 20180715 张怡 生日会
datetime: 2018-07-15T16:45:00+08:00
vod: http://zhibo.ckg48.com/Index/invedio/id/661
m3u8: http://ts.snh48.com/vod/zhangyishengrihui.mp4/playlist.m3u8
tags:
- SNH48
thumbnail: 
playlists:
- 全部
- 全部公演
- 特别公演
