title: 20180513 Team HⅡ New H Stars 07
datetime: 2018-05-13T19:30:00+08:00
vod: http://zhibo.ckg48.com/Index/invedio/id/578
m3u8: http://ts.snh48.com/chaoqing/9999/20180513174303-playlist.m3u8?beginTime=20180513193000&endTime=20180513212400
tags:
- SNH48
- New H Stars
- Team HⅡ
- HⅡ
- Team HII
- HII
thumbnail: 20180513-New H Stars-07.png
playlists:
- 全部
- 全部公演
- Team HⅡ
- Team HⅡ — New H Stars
