title: 20180331 Team HⅡ New H Stars 02
datetime: 2018-03-31T19:00:00+08:00
vod: http://zhibo.ckg48.com/Index/invedio/id/526
m3u8: http://ts.snh48.com/chaoqing/9999/20180331182614-playlist.m3u8?beginTime=20180331190000&endTime=20180331213500
tags:
- SNH48
- New H Stars
- Team HⅡ
- HⅡ
- Team HII
- HII
thumbnail: 20180331-New H Stars-02.png
playlists:
- 全部
- 全部公演
- Team HⅡ
- Team HⅡ — New H Stars
