title: 20180429 Team HⅡ New H Stars 06
datetime: 2018-04-29T19:00:00+08:00
vod: http://zhibo.ckg48.com/Index/invedio/id/560
m3u8: http://ts.snh48.com/chaoqing/9999/20180429184441-playlist.m3u8?beginTime=20180429190000&endTime=20180429214700
tags:
- SNH48
- New H Stars
- Team HⅡ
- HⅡ
- Team HII
- HII
thumbnail: 20180429-New H Stars-06.png
playlists:
- 全部
- 全部公演
- Team HⅡ
- Team HⅡ — New H Stars
